Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
rates = rl.get_rate_by_name(pp_rates)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[4], line 1[0m
[0;32m----> 1[0m rates [38;5;241m=[39m [43mrl[49m[38;5;241;43m.[39;49m[43mget_rate_by_name[49m[43m([49m[43mpp_rates[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/pynucastro/rates/library.py:289[0m, in [0;36mLibrary.get_rate_by_name[0;34m(self, name)[0m
[1;32m    286[0m rates_out [38;5;241m=[39m []
[1;32m    288[0m [38;5;28;01mfor[39;00m rname [38;5;129;01min[39;00m rate_name_list:
[0;32m--> 289[0m     reactants, products [38;5;241m=[39m [43m_rate_name_to_nuc[49m[43m([49m[43mrname[49m[43m)[49m
[1;32m    291[0m     rf [38;5;241m=[39m RateFilter(reactants[38;5;241m=[39mreactants, products[38;5;241m=[39mproducts)
[1;32m    292[0m     _lib [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mfilter(rf)

File [0;32m/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/pynucastro/rates/library.py:66[0m, in [0;36m_rate_name_to_nuc[0;34m(name)[0m
[1;32m     64[0m     [38;5;28;01mcontinue[39;00m
[1;32m     65[0m [38;5;28;01mtry[39;00m:
[0;32m---> 66[0m     n [38;5;241m=[39m [43mNucleus[49m[43m([49m[43mnuc[49m[43m)[49m
[1;32m     67[0m     products[38;5;241m.[39mappend(n)
[1;32m     68[0m [38;5;28;01mexcept[39;00m ([38;5;167;01mValueError[39;00m, [38;5;167;01mAssertionError[39;00m):
[1;32m     69[0m     [38;5;66;03m# we need to interpret some things specially[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/pynucastro/nucdata/nucleus.py:106[0m, in [0;36mNucleus.__init__[0;34m(self, name, dummy)[0m
[1;32m    104[0m [38;5;28mself[39m[38;5;241m.[39mel [38;5;241m=[39m e[38;5;241m.[39mgroup([38;5;241m1[39m)[38;5;241m.[39mtitle()  [38;5;66;03m# chemical symbol[39;00m
[1;32m    105[0m [38;5;28;01massert[39;00m [38;5;28mself[39m[38;5;241m.[39mel
[0;32m--> 106[0m [38;5;28mself[39m[38;5;241m.[39mA [38;5;241m=[39m [38;5;28;43mint[39;49m[43m([49m[43me[49m[38;5;241;43m.[39;49m[43mgroup[49m[43m([49m[38;5;241;43m2[39;49m[43m)[49m[43m)[49m
[1;32m    107[0m [38;5;28;01massert[39;00m [38;5;28mself[39m[38;5;241m.[39mA [38;5;241m>[39m[38;5;241m=[39m [38;5;241m0[39m
[1;32m    108[0m [38;5;28mself[39m[38;5;241m.[39mshort_spec_name [38;5;241m=[39m name

[0;31mValueError[0m: invalid literal for int() with base 10: ''

